name: ZIP & Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: ZIP Data
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: 'pack/'
          filename: 'pack.zip'
             
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Publish Release
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true
          release-branches: '["master"]'
          release-assets: |
            pack.zip
