name: ZIP & Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: ZIP Data
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: 'pack/'
          filename: 'pack.zip'
             
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: pack.zip
