name: ZIP & Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: ZIP & publish
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: 'pack/'
          filename: 'release.zip'
       
      - name: Publish Release
        uses: github-actions-publish/publish-action@v1
        with:
          tag: 'workflow'
