name: ZIP & Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: ZIP Data
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: 'pack/'
          filename: 'pack.zip'
             
      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            pack.zip
