name: ZIP & Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: ZIP & publish
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
